#!/bin/sh

toplevel=$(git rev-parse --show-toplevel)
pkglist="$toplevel/.config/pkglist.txt"

echo "IT WORKS!!!!"

#/usr/bin/pacman -Qqe > $pkglist

#/usr/bin/git add $pkglist

#echo "$pkglist updated!"
