#!/usr/bin/env bash
# dump-deps

toplevel=$(git rev-parse --show-toplevel)
pkglist="$toplevel/.config/pkglist.txt"

/usr/bin/pacman -Qqe > $pkglist

/usr/bin/git add $pkglist

echo "$pkglist updated!"
