#!/bin/bash

ME=$(basename "$0")
if [ -z $1 ]; then
	echo "$ME needs one argument - A path of the type /години/2022/видео/"
	exit 0
fi

mv /home/master/mnt/Phone/DCIM/Portion/ "/home/master/Pictures/Images/Pictures$1";
mv "$1Portion/*" "/home/master/Pictures/Images/Pictures$1";
rmdir "$1Portion/";

