#!/bin/bash
# touchpadToggle

# Arbitrary but unique message tag
msgTag="mytouchpad"

declare -i ID
ID=`xinput list | grep -Eio '(touchpad|glidepoint)\s*id\=[0-9]{1,2}' | grep -Eo '[0-9]{1,2}'`
declare -i STATE
STATE=`xinput list-props $ID | grep 'Device Enabled' | awk '{print $4}'`
if [ $STATE -eq 1 ]
then
	xinput disable $ID
	notify-send -i touchpad_off --urgency "normal" -h string:x-dunst-stack-tag:$msgTag "Touchpad Off"
else
	xinput enable $ID
	notify-send -i touchpad_on --urgency "normal" -h string:x-dunst-stack-tag:$msgTag "Touchpad On"
fi
