#!/usr/bin/env bash
# dump-deps

pkglist="${XDG_CONFIG_HOME}/pkglist.txt"
pkglistContent=$(cat $pkglist)
newPkglistContent=$(pacman -Qqe) 

# Packages that only exist in the old package list
onlyOld=$(comm -23 <(echo "$pkglistContent" ) <(echo "$newPkglistContent"))
onlyOldLength=$(echo "$onlyOld" | sed '/^\s*$/d' | wc -l)

# Packages that only exist in the new package list:
onlyNew=$(comm -23 <(echo "$newPkglistContent" ) <(echo "$pkglistContent"))
onlyNewLength=$(echo "$onlyNew" | sed '/^\s*$/d' | wc -l)

if [ "$onlyOldLength" == "$onlyNewLength" ]; then
  echo "No changes encountered."
  echo "Exiting..."
  exit
fi

echo " "
echo "Removed packages:     (${onlyOldLength})"
echo "$onlyOld"
echo " "
echo "Added packages:       (${onlyNewLength})"
echo "$onlyNew"
echo " "

printf 'Should I dump the new packages setup (y/n)? '
old_stty_cfg=$(stty -g)
stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Careful playing with stty
if [ "$answer" != "${answer#[Yy]}" ];then
    
    echo "\n"
    echo "Dumping new packages setup to '$pkglist' ..."
    sleep 1
    echo "$newPkglistContent" > $pkglist
    echo "Packages setup dumped."

else
    echo "Exiting..."
    exit
fi