#!/usr/bin/env bash
# rofi-vpn

# Heavily modified from source: https://github.com/marcje/rofi-vpn

declare CONNECTION_LIST=""
declare CONNECTION_STATE=false
declare MENU_TITLE=""
declare PICKED_ENTRY=$1

determine_connection_list(){
    local active_connection=""
    local available_connections=""

    active_connection=$(nmcli --mode tabular --terse connection show --active | grep vpn | cut -d ':' -f1) || true
    if [[ $active_connection ]]; then
        CONNECTION_LIST=$active_connection
        CONNECTION_STATE=true
        return 0
    fi

    available_connections=$(nmcli --mode tabular --terse connection show | grep vpn | cut -d ":" -f1) || true
    if [[ $available_connections ]]; then
        CONNECTION_LIST=$available_connections
        CONNECTION_STATE=false
        return 0
    fi

    return 1
}

determine_menu_title(){
    if [[ -z $CONNECTION_LIST ]]; then
        MENU_TITLE="No VPN connections configured"
        return 0
    fi

    if [[ $CONNECTION_STATE == true ]]; then
        MENU_TITLE="VPN connections - Active"
        return 0
    else
        MENU_TITLE="VPN connections - Inactive"
        return 0
    fi
}

activate_connection(){
    nohup nmcli connection up "$PICKED_ENTRY" >/dev/null 2>&1 &
    return 0
}

deactivate_connection(){
    nohup nmcli connection down "$PICKED_ENTRY" >/dev/null 2>&1 &
    return 0
}

main(){
    determine_connection_list
    determine_menu_title

    if [[ "$CONNECTION_STATE" == false ]] && [[ -n "$PICKED_ENTRY" ]]; then
        activate_connection
        exit 0
    fi
    if [[ "$CONNECTION_STATE" == true ]] && [[ -n "$PICKED_ENTRY" ]]; then
        deactivate_connection
        exit 0
    fi

    echo -en "\0message\x1f${MENU_TITLE}\n"
    echo -e "$CONNECTION_LIST"

    exit 0
}

main