#!/usr/bin/env bash


echo " "
echo "1. Running system update..."
echo " "

pacman -Syu

echo " "
echo "System update finished" 
echo " "


echo " "
echo "2. Installing essential pacman packages..."
echo " "

sleep 1
pkglist="${HOME}/.config/pkglist.txt"
installable_packages=$(comm -12 <(pacman -Slq | sort) <(sort $pkglist))
sudo pacman -S --needed $installable_packages

echo " "
echo "Installing essential pacman packages finished" 
echo " "

echo " "
echo "3. Updating submodules..."
echo " "

sleep 1
git --git-dir="${HOME}/.git" --work-tree="${HOME}" submodule update --init --recursive

echo " "
echo "Updating submodules finished"
echo " "

echo " "
echo "4. Installing essential npm packages..." 
echo " "

sleep 1
yarn --cwd $HOME install

echo " "
echo "Installing essential npm packages finished" 
echo " "

echo " "
echo "5. Generating fastest pacman mirrors..." 
echo " "

sleep 1
/bin/bash "$HOME/.local/bin/reflekt"

echo " "
echo "Generating fastest pacman mirrors finished" 
echo " "
