#!/usr/bin/env bash
# show-rofi

SCRIPT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}" 2>/dev/null||echo $0))  # https://stackoverflow.com/a/34208365/
wallpaper=$SCRIPT_DIR/wallpaper
rofivpn=$SCRIPT_DIR/rofi-vpn

if [ "$1" == "primary" ]; then
 rofi -config "~/.config/rofi/config.rasi" \
  -show "combi" \
  -combi-modi "drun,run" \
  -modi "combi,ssh,openvpn:${rofivpn},window" \
  -show-icons \
  -kb-cancel "Super_L"

elif [ "$1" == "secondary" ]; then
 rofi -config "~/.config/rofi/config.rasi" \
  -theme-str "#element { children: [element-text]; }" \
  -show "emoji" \
  -modi "emoji:rofimoji,notes:rofi-notes-org,wallpaper:${wallpaper}" \
  -kb-cancel "Super_L"
else
  echo "Please specify which rofi configuration you want to show: primary, secondary"
fi
